export const Bewertung = ["Hervorragend", "Fabelhaft", "Sehr gut", "Gut"];
export const Ausstatungen = [
  "Parkplatz",
  "WLAN inklusive",
  "Restaurant",
  "Bar",
  "Haustiere erlaubt",
  "Zimmerservice",
  "24-Stunden-Rezeption",
  "Fitnesscenter",
  "Nichtraucherzimmer",
  "Flughafenshuttle",
  "Einrichtungen für behinderte Gäste",
  "Familienzimmer",
  "Spa & Wellnesscenter",
  "Aufladestation für Elektro-Autos",
  "Pool",
  "Hervorragendes Frühstück",
];
export const Freizeit = [
  "Wandern",
  "Radfahren",
  "Wassersportmöglichkeiten vor Ort",
  "Angeln",
  "Windsurfen",
  "Skifahren",
  "Fahrradtouren",
];
export const Sehenswürdigkeiten = [
  "Bahnhof Friedrichshafen",
  "Fähre Friedrichshafen",
  "Zeppelin Museum",
  "Stadtmuseum Lindau",
  "Lindauer Leuchtturm",
  "Hauptbahnhof Lindau",
  "Hafen Lindau",
  "Hafen Konstanz",
  "Casino Bregenz",
  "Seebühne",
  "Bregenzer Festspiele",
  "Vorarlberger Landesmuseum",
  "Stiftsbibliothek",
  "Textilmuseum",
  "Pfänderbahn",
  "Dornbirner Messe",
  "Inatura",
  "Klosterinsel Reichenau im Bodensee",
  "Messe Friedrichshafen",
  "Bahnhof Dornbirn",
  "Karrenseilbahn",
  "Burg Hohenklingen",
  "Bodensee-Universität",
  "Arena Konstanz",
];
export const ZimmerAusstattung = [
  "Privater Pool",
  "Meerblick",
  "Klimaanlage",
  "Eigenes Badezimmer",
  "Küche/Kochnische",
  "Balkon",
  "Whirlpool",
  "Dusche",
  "Gemeinschaftsbad",
  "Aussicht",
  "Kühlschrank",
  "Pool mit Ausblick",
  "Terrasse",
  "TV",
  "WC",
  "Seeblick",
  "Whirlpool-Badewanne",
  "Handtücher",
  "Toilettenpapier",
  "Bettwäsche",
  "Flachbild-TV",
  "Infinity-Pool",
  "Rooftop-Pool",
  "Badewanne",
  "Sauna",
  "Haartrockner",
];

// Unterkunfttyp
export const Arten = [
  "Hotel",
  "Motel",
  "Ferienwohnung",
  "Ferienhaus",
  "Pension",
  "Privatzimmer",
];

export const HotelListArray = [
  //   {
  //     id: 1,                     // number
  //     art: "",                   // string
  //     name: ,                    // string
  //     stern: ,                   // number
  //     level: ,                   // 1 : Preferred-Plus-Unterkunft, 2 : Preferred Unterkunft
  //     nachhaltiger: ,            // number
  //     punktzahl: ,               // number
  //     qualitat: ,                // string
  //     bewertung: ,               // number
  //     stadt: ,                   // string
  //     adresse: ,                 // string
  //     strandzugang: ,            // 0 oder 1
  //     erklarung: ,               // string
  //     ausstatung: [],            // array
  //     freizeit: [],              // array
  //     sehenswürdigkeiten: [],    // array
  //     zimmerausstattung: [],     // array
  //     preise: ,                  // number
  //     hauptbild: ,               // string
  //     bilder: [],                // array
  //   },
  {
    id: 1,
    art: "Hotel",
    name: "Das Flint",
    stern: 4,
    level: 1,
    nachhaltiger: 2,
    punktzahl: 8.9,
    qualitat: "Fabelhaft",
    bewertung: 616,
    stadt: "Dornbirn",
    adresse:
      "Bahnhofstraße, Franz-Michael-Felder-Straße, 6850 Dornbirn, Österreich",
    strandzugang: 0,
    erklarung:
      "Das Flint in Dornbirn liegt 3,2 km von der Messe Dornbirn entfernt und bietet Unterkünfte mit einem Garten, Privatparkplätzen, einer Gemeinschaftslounge und einer Terrasse. Jede Unterkunft in diesem 4-Sterne-Hotel bietet Stadtblick und Zugang zu einer Sauna. Verweilen Sie auch bei einem Getränk an der Bar. Das Hotel bietet Ihnen klimatisierte Zimmer mit einem Kleiderschrank, einem Wasserkocher, einem Kühlschrank, einem Safe, einem Flachbild-TV und einem eigenen Bad mit einer Dusche. Ausgewählte Zimmer verfügen über eine Küche mit einem Geschirrspüler und einem Kochfeld. Jedes Zimmer im Das Flint ist mit Bettwäsche und Handtüchern ausgestattet.",
    ausstatung: [
      "Parkplatz",
      "WLAN inklusive",
      "Restaurant",
      "Bar",
      "Haustiere erlaubt",
      "Zimmerservice",
      "24-Stunden-Rezeption",
      "Fitnesscenter",
      "Nichtraucherzimmer",
      "Flughafenshuttle",
      "Einrichtungen für behinderte Gäste",
      "Familienzimmer",
      "Spa & Wellnesscenter",
      "Aufladestation für Elektro-Autos",
      "Pool",
      "Hervorragendes Frühstück",
    ],
    freizeit: [
      "Wandern",
      "Radfahren",
      "Wassersportmöglichkeiten vor Ort",
      "Angeln",
      "Windsurfen",
      "Skifahren",
      "Fahrradtouren",
    ],
    sehenswürdigkeiten: [
      "Bahnhof Friedrichshafen",
      "Fähre Friedrichshafen",
      "Zeppelin Museum",
      "Stadtmuseum Lindau",
      "Lindauer Leuchtturm",
      "Hauptbahnhof Lindau",
      "Hafen Lindau",
      "Hafen Konstanz",
      "Casino Bregenz",
      "Seebühne",
      "Bregenzer Festspiele",
      "Vorarlberger Landesmuseum",
      "Stiftsbibliothek",
      "Textilmuseum",
      "Pfänderbahn",
      "Dornbirner Messe",
      "Inatura",
      "Klosterinsel Reichenau im Bodensee",
      "Messe Friedrichshafen",
      "Bahnhof Dornbirn",
      "Karrenseilbahn",
      "Burg Hohenklingen",
      "Bodensee-Universität",
      "Arena Konstanz",
    ],
    zimmerausstattung: [
      "Privater Pool",
      "Meerblick",
      "Klimaanlage",
      "Eigenes Badezimmer",
      "Küche/Kochnische",
      "Balkon",
      "Whirlpool",
      "Dusche",
      "Aussicht",
      "Kühlschrank",
      "Pool mit Ausblick",
      "Terrasse",
      "TV",
      "WC",
      "Seeblick",
      "Whirlpool-Badewanne",
      "Handtücher",
      "Toilettenpapier",
      "Bettwäsche",
      "Flachbild-TV",
      "Infinity-Pool",
      "Rooftop-Pool",
      "Badewanne",
      "Sauna",
      "Haartrockner",
    ],
    preise: 229,
    hauptbild: "H01-1.jpg",
    bilder: ["H01-1.jpg", "H01-2.jpg", "H01-3.jpg", "H01-4.jpg"],
  },
  {
    id: 2,
    art: "Hotel",
    name: "Hotel & Tagungszentrum Schloss Hohenfels",
    stern: 0,
    level: 2,
    nachhaltiger: 1,
    punktzahl: 8.5,
    qualitat: "Sehr gut",
    bewertung: 87,
    stadt: "Hohenfels",
    adresse: "Schloss Hohenfels 1, 78355 Hohenfels, Deutschland",
    strandzugang: 0,
    erklarung:
      "Das Hotel & Tagungszentrum Schloss Hohenfels in Hohenfels liegt 41 km von der Klosterinsel Reichenau und 43 km vom Hauptbahnhof Konstanz entfernt und bietet Unterkünfte mit einem Garten sowie kostenfreie Privatparkplätze. Die Unterkunft bietet Familienzimmer und eine Sonnenterrasse. Die Unterkunft ist allergikerfreundlich und liegt 47 km vom Messegelände Friedrichshafen entfernt.",
    ausstatung: [
      "Parkplatz",
      "Restaurant",
      "Bar",
      "Nichtraucherzimmer",
      "Hervorragendes Frühstück",
    ],
    freizeit: ["Wandern", "Radfahren"],
    sehenswürdigkeiten: [
      "Bahnhof Friedrichshafen",
      "Fähre Friedrichshafen",
      "Zeppelin Museum",
      "Stadtmuseum Lindau",
      "Lindauer Leuchtturm",
      "Hauptbahnhof Lindau",
      "Hafen Lindau",
      "Hafen Konstanz",
      "Casino Bregenz",
      "Seebühne",
      "Bregenzer Festspiele",
      "Vorarlberger Landesmuseum",
      "Stiftsbibliothek",
      "Textilmuseum",
      "Pfänderbahn",
      "Dornbirner Messe",
      "Inatura",
      "Klosterinsel Reichenau im Bodensee",
      "Messe Friedrichshafen",
      "Bahnhof Dornbirn",
      "Karrenseilbahn",
      "Burg Hohenklingen",
      "Bodensee-Universität",
      "Arena Konstanz",
    ],
    zimmerausstattung: [
      "Heizung",
      "Eigenes Badezimmer",
      "Dusche",
      "Aussicht",
      "Terrasse",
      "Handtücher",
      "Toilettenpapier",
      "Bettwäsche",
      "Badewanne",
      "Haartrockner",
    ],
    preise: 278,
    hauptbild: "H02-1.jpg",
    bilder: ["H02-1.jpg", "H02-2.jpg", "H02-3.jpg", "H02-4.jpg"],
  },
  {
    id: 3,
    art: "Ferienhaus",
    name: "BnB Fliegerhaeusle Hagnau 24h Self Check In",
    stern: 0,
    level: 0,
    nachhaltiger: 3,
    punktzahl: 7.6,
    qualitat: "Gut",
    bewertung: 616,
    stadt: "Hagnau am Bodensee",
    adresse: "Hauptstraße 15/1, 88709 Hagnau am Bodensee, Deutschland",
    strandzugang: 1,
    erklarung:
      "Das BnB Fliegerhaeusle Hagnau 24h Self Check In in in Hagnau liegt 18 km vom Messegelände Friedrichshafen entfernt und bietet Unterkünfte mit einer Terrasse, kostenfreie Privatparkplätze und ein Restaurant. Der Gasthof mit kostenfreiem WLAN liegt etwa 41 km vom Bahnhof Lindau und 48 km vom Bahnhof Bregenz entfernt. Die Nichtraucherunterkunft liegt 48 km vom Casino Bregenz entfernt.",
    ausstatung: [
      "Parkplatz",
      "WLAN inklusive",
      "Restaurant",
      "Bar",
      "Nichtraucherzimmer",
      "Einrichtungen für behinderte Gäste",
      "Spa & Wellnesscenter",
      "Hervorragendes Frühstück",
    ],
    freizeit: ["Wandern", "Radfahren", "Fahrradtouren"],
    sehenswürdigkeiten: [
      "Bahnhof Friedrichshafen",
      "Fähre Friedrichshafen",
      "Zeppelin Museum",
      "Hafen Lindau",
      "Hafen Konstanz",
      "Seebühne",
      "Bregenzer Festspiele",
      "Vorarlberger Landesmuseum",
      "Klosterinsel Reichenau im Bodensee",
      "Messe Friedrichshafen",
      "Bahnhof Dornbirn",
      "Karrenseilbahn",
      "Burg Hohenklingen",
      "Bodensee-Universität",
    ],
    zimmerausstattung: [
      "Privater Pool",
      "Klimaanlage",
      "Heizung",
      "Eigenes Badezimmer",
      "Dusche",
      "Aussicht",
      "Kühlschrank",
      "Terrasse",
      "TV",
      "WC",
      "Handtücher",
      "Toilettenpapier",
      "Bettwäsche",
      "Flachbild-TV",
      "Badewanne",
      "Haartrockner",
    ],
    preise: 248,
    hauptbild: "H03-1.jpg",
    bilder: ["H03-1.jpg", "H03-2.jpg", "H03-3.jpg", "H03-4.jpg"],
  },
  {
    id: 4,
    art: "Ferienwohnung",
    name: "Jollen Apartments",
    stern: 3,
    level: 0,
    nachhaltiger: 2,
    punktzahl: 8.1,
    qualitat: "Sehr gut",
    bewertung: 616,
    stadt: "Friedrichshafen",
    adresse: "Goethestraße 9, 88046 Friedrichshafen, Deutschland",
    strandzugang: 0,
    erklarung:
      "Die Jollen Apartments in Friedrichshafen in Baden-Württemberg bieten Unterkünfte mit kostenfreiem WLAN und kostenfreien Privatparkplätzen. Jede Wohneinheit ist komplett mit einer Waschmaschine, einem Flachbild-Sat-TV, einem Schlafsofa und einem Kleiderschrank ausgestattet. Die Küche ist mit einem Kühlschrank, einem Geschirrspüler, einem Backofen und einer Kaffeemaschine ausgestattet.",
    ausstatung: ["Parkplatz", "WLAN inklusive", "Nichtraucherzimmer"],
    freizeit: ["Wandern", "Radfahren", "Fahrradtouren"],
    sehenswürdigkeiten: [
      "Zeppelin Museum",
      "Stadtmuseum Lindau",
      "Lindauer Leuchtturm",
      "Hauptbahnhof Lindau",
      "Hafen Lindau",
      "Hafen Konstanz",
      "Casino Bregenz",
      "Stiftsbibliothek",
      "Textilmuseum",
      "Pfänderbahn",
      "Dornbirner Messe",
      "Messe Friedrichshafen",
      "Burg Hohenklingen",
      "Bodensee-Universität",
      "Arena Konstanz",
    ],
    zimmerausstattung: [
      "Klimaanlage",
      "Heizung",
      "Eigenes Badezimmer",
      "Dusche",
      "Aussicht",
      "Kühlschrank",
      "Terrasse",
      "TV",
      "WC",
      "Toilettenpapier",
      "Bettwäsche",
      "Haartrockner",
    ],
    preise: 160,
    hauptbild: "H04-1.jpg",
    bilder: ["H04-1.jpg", "H04-2.jpg", "H04-3.jpg", "H04-4.jpg"],
  },
  {
    id: 5,
    art: "Pension",
    name: "Hotel Rad",
    stern: 0,
    level: 0,
    nachhaltiger: 1,
    punktzahl: 8.2,
    qualitat: "Sehr gut",
    bewertung: 1080,
    stadt: "Tettnang",
    adresse: "Lindauer Straße 2, 88069 Tettnang, Deutschland",
    strandzugang: 0,
    erklarung:
      "Diese unverwechselbare Fachwerk-Pension heißt ihre Gäste seit mehr als 500 Jahren in einer anspruchsvollen Atmosphäre willkommen. WLAN nutzen Sie kostenfrei. Diese liebevoll restaurierte Unterkunft bietet Ihnen sorgfältig gepflegte Zimmer in einem historischen Ambiente. Die Gastgeber setzen alles daran, um Ihren Aufenthalt so angenehm wie möglich zu gestalten.",
    ausstatung: [
      "Parkplatz",
      "WLAN inklusive",
      "Restaurant",
      "Bar",
      "Nichtraucherzimmer",
      "Einrichtungen für behinderte Gäste",
      "Spa & Wellnesscenter",
      "Hervorragendes Frühstück",
    ],
    freizeit: ["Wandern", "Radfahren", "Fahrradtouren"],
    sehenswürdigkeiten: [
      "Hauptbahnhof Lindau",
      "Hafen Lindau",
      "Hafen Konstanz",
      "Casino Bregenz",
      "Seebühne",
      "Stiftsbibliothek",
      "Textilmuseum",
      "Pfänderbahn",
      "Klosterinsel Reichenau im Bodensee",
      "Messe Friedrichshafen",
      "Bahnhof Dornbirn",
      "Karrenseilbahn",
      "Burg Hohenklingen",
      "Arena Konstanz",
    ],
    zimmerausstattung: [
      "Privater Pool",
      "Heizung",
      "Eigenes Badezimmer",
      "Dusche",
      "Aussicht",
      "Kühlschrank",
      "Terrasse",
      "TV",
      "WC",
      "Handtücher",
      "Toilettenpapier",
      "Bettwäsche",
      "Badewanne",
      "Haartrockner",
    ],
    preise: 265,
    hauptbild: "H05-1.jpg",
    bilder: ["H05-1.jpg", "H05-2.jpg", "H05-3.jpg", "H05-4.jpg"],
  },
  {
    id: 6,
    art: "Privatzimmer",
    name: "City Home St Gallen",
    stern: 0,
    level: 0,
    nachhaltiger: 1,
    punktzahl: 7.1,
    qualitat: "Gut",
    bewertung: 152,
    stadt: "St. Gallen",
    adresse: "28 Zürcherstrasse, 9000 St. Gallen, Schweiz",
    strandzugang: 0,
    erklarung:
      "Das City Home St Gallen in St. Gallen liegt 3,1 km vom Olma Messen St. Gallen und 31 km vom Säntis entfernt und bietet Unterkünfte mit kostenfreiem WLAN und ein Restaurant. Die Messe Dornbirn liegt 37 km von der Privatunterkunft entfernt und das Casino Bregenz erreichen Sie nach 39 km. Der nächstgelegene Flughafen ist der 23 km vom City Home St Gallen entfernte Flughafen St. Gallen-Altenrhein.",
    ausstatung: ["Parkplatz", "WLAN inklusive"],
    freizeit: ["Wandern", "Radfahren"],
    sehenswürdigkeiten: [
      "Hauptbahnhof Lindau",
      "Seebühne",
      "Stiftsbibliothek",
      "Textilmuseum",
      "Pfänderbahn",
      "Klosterinsel Reichenau im Bodensee",
      "Messe Friedrichshafen",
      "Bahnhof Dornbirn",
      "Burg Hohenklingen",
    ],
    zimmerausstattung: [
      "Heizung",
      "Gemeinschaftsbad",
      "Aussicht",
      "Kühlschrank",
      "TV",
      "WC",
      "Handtücher",
      "Toilettenpapier",
      "Bettwäsche",
    ],
    preise: 265,
    hauptbild: "H06-1.jpg",
    bilder: ["H06-1.jpg", "H06-2.jpg", "H06-3.jpg", "H06-4.jpg"],
  },
  {
    id: 7,
    art: "Motel",
    name: "Fairmotel Dornbirn",
    stern: 4,
    level: 1,
    nachhaltiger: 3,
    punktzahl: 8.5,
    qualitat: "Sehr gut",
    bewertung: 960,
    stadt: "Dornbirn",
    adresse: "Wallenmahd 15, 6850 Dornbirn, Österreich",
    strandzugang: 0,
    erklarung:
      "Dieses moderne Hotel in Privatbesitz liegt am grünen Stadtrand von Dornbirn, nur wenige Minuten von der Innenstadt und von der Autobahn A14 entfernt. Das Fairmotel Dornbirn bietet geräumige und komfortable Zimmer und Apartments, eine Bar, einen Seminarraum, kostenfreie Parkplätze und kostenfreien Internetzugang. Auch eine Lobby mit Sitzecke und Plasma-TV, eine Cafeteria-Ecke und ein Internet-Terminal stehen zur Verfügung.",
    ausstatung: [
      "Parkplatz",
      "WLAN inklusive",
      "Restaurant",
      "Bar",
      "Haustiere erlaubt",
      "Zimmerservice",
      "Fitnesscenter",
      "Nichtraucherzimmer",
      "Flughafenshuttle",
      "Familienzimmer",
      "Spa & Wellnesscenter",
      "Pool",
      "Hervorragendes Frühstück",
    ],
    freizeit: ["Wandern", "Radfahren", "Angeln", "Windsurfen", "Skifahren"],
    sehenswürdigkeiten: [
      "Zeppelin Museum",
      "Stadtmuseum Lindau",
      "Lindauer Leuchtturm",
      "Hauptbahnhof Lindau",
      "Hafen Lindau",
      "Hafen Konstanz",
      "Casino Bregenz",
      "Seebühne",
      "Bregenzer Festspiele",
      "Textilmuseum",
      "Pfänderbahn",
      "Dornbirner Messe",
      "Inatura",
      "Klosterinsel Reichenau im Bodensee",
      "Messe Friedrichshafen",
      "Bahnhof Dornbirn",
      "Karrenseilbahn",
      "Burg Hohenklingen",
    ],
    zimmerausstattung: [
      "Eigenes Badezimmer",
      "Balkon",
      "Dusche",
      "Aussicht",
      "Kühlschrank",
      "TV",
      "WC",
      "Handtücher",
      "Toilettenpapier",
      "Bettwäsche",
      "Flachbild-TV",
      "Badewanne",
      "Haartrockner",
    ],
    preise: 360,
    hauptbild: "H07-1.jpg",
    bilder: ["H07-1.jpg", "H07-2.jpg", "H07-3.jpg", "H07-4.jpg"],
  },
];
